// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use crate::api::realtime::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1254621049;

// Section: executor

pub use crate::api::simple::FLUTTER_RUST_BRIDGE_HANDLER;

// Section: wire_funcs

fn wire__crate__api__realtime__RealtimeAnalyzer_finish_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "RealtimeAnalyzer_finish",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let mut api_that_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_that, 0, true,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_that_guard = Some(api_that.lockable_decode_sync_ref_mut()),
                        _ => unreachable!(),
                    }
                }
                let mut api_that_guard = api_that_guard.unwrap();
                let output_ok = Result::<_, ()>::Ok(
                    crate::api::realtime::RealtimeAnalyzer::finish(&mut *api_that_guard),
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__realtime__RealtimeAnalyzer_new_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "RealtimeAnalyzer_new",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sample_rate = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::realtime::RealtimeAnalyzer::new(
                    api_sample_rate,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__realtime__RealtimeAnalyzer_push_pcm16_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "RealtimeAnalyzer_push_pcm16",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>,
            >>::sse_decode(&mut deserializer);
            let api_pcm = <Vec<i16>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let mut api_that_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_that, 0, true,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_that_guard = Some(api_that.lockable_decode_sync_ref_mut()),
                        _ => unreachable!(),
                    }
                }
                let mut api_that_guard = api_that_guard.unwrap();
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::realtime::RealtimeAnalyzer::push_pcm16(
                        &mut *api_that_guard,
                        api_pcm,
                    ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__realtime__RealtimeAnalyzer_push_pcm16_at_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "RealtimeAnalyzer_push_pcm16_at",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>,
            >>::sse_decode(&mut deserializer);
            let api_start_sample = <u64>::sse_decode(&mut deserializer);
            let api_pcm = <Vec<i16>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let mut api_that_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_that, 0, true,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_that_guard = Some(api_that.lockable_decode_sync_ref_mut()),
                        _ => unreachable!(),
                    }
                }
                let mut api_that_guard = api_that_guard.unwrap();
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::realtime::RealtimeAnalyzer::push_pcm16_at(
                        &mut *api_that_guard,
                        api_start_sample,
                        api_pcm,
                    ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__realtime__RealtimeAnalyzer_push_pcm16_with_metadata_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "RealtimeAnalyzer_push_pcm16_with_metadata",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>,
            >>::sse_decode(&mut deserializer);
            let api_start_sample = <u64>::sse_decode(&mut deserializer);
            let api_pcm = <Vec<i16>>::sse_decode(&mut deserializer);
            let api_dropped_samples_before = <u32>::sse_decode(&mut deserializer);
            let api_discontinuity_before = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let mut api_that_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_that, 0, true,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_that_guard = Some(api_that.lockable_decode_sync_ref_mut()),
                        _ => unreachable!(),
                    }
                }
                let mut api_that_guard = api_that_guard.unwrap();
                let output_ok = Result::<_, ()>::Ok(
                    crate::api::realtime::RealtimeAnalyzer::push_pcm16_with_metadata(
                        &mut *api_that_guard,
                        api_start_sample,
                        api_pcm,
                        api_dropped_samples_before,
                        api_discontinuity_before,
                    ),
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__realtime__RealtimeAnalyzer_reset_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "RealtimeAnalyzer_reset",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let mut api_that_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_that, 0, true,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_that_guard = Some(api_that.lockable_decode_sync_ref_mut()),
                        _ => unreachable!(),
                    }
                }
                let mut api_that_guard = api_that_guard.unwrap();
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::realtime::RealtimeAnalyzer::reset(&mut *api_that_guard);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::simple::init_app();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__song__probe_song_separation_runtime_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "probe_song_separation_runtime",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_model_path = <String>::sse_decode(&mut deserializer);
            let api_expected_model_sha256 = <String>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::song::SongRuntimeStatusDto,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::song::probe_song_separation_runtime(
                        api_model_path,
                        api_expected_model_sha256,
                        api_sink,
                    );
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__song_compare__start_reference_analysis_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_reference_analysis",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::api::song_compare::ReferenceAnalysisRequestDto>::sse_decode(
                &mut deserializer,
            );
            let api_sink = <StreamSink<
                crate::api::song_compare::ReferenceAnalysisEventDto,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::song_compare::start_reference_analysis(api_request, api_sink);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__song__start_song_separation_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_song_separation",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::song::SongSeparationRequestDto>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::song::SongSeparationEventDto,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::song::start_song_separation(api_request, api_sink);
                })?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: related_funcs

flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>
);

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for RealtimeAnalyzer {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueMoi<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return decode_rust_opaque_moi(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::song_compare::ReferenceAnalysisEventDto,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::song::SongRuntimeStatusDto,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::song::SongSeparationEventDto,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::realtime::AnalysisFrameDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_startSample = <u64>::sse_decode(deserializer);
        let mut var_rmsDbfs = <f32>::sse_decode(deserializer);
        let mut var_peakDbfs = <f32>::sse_decode(deserializer);
        let mut var_pitchHz = <Option<f32>>::sse_decode(deserializer);
        let mut var_pitchClarity = <f32>::sse_decode(deserializer);
        let mut var_voiced = <bool>::sse_decode(deserializer);
        let mut var_bandPowersDbfs = <Vec<f32>>::sse_decode(deserializer);
        let mut var_qualityFlags = <u16>::sse_decode(deserializer);
        return crate::api::realtime::AnalysisFrameDto {
            start_sample: var_startSample,
            rms_dbfs: var_rmsDbfs,
            peak_dbfs: var_peakDbfs,
            pitch_hz: var_pitchHz,
            pitch_clarity: var_pitchClarity,
            voiced: var_voiced,
            band_powers_dbfs: var_bandPowersDbfs,
            quality_flags: var_qualityFlags,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::realtime::AnalysisFrameDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::realtime::AnalysisFrameDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<f32>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<i16> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<i16>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::song_compare::ReferenceFeatureFrameDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(
                <crate::api::song_compare::ReferenceFeatureFrameDto>::sse_decode(deserializer),
            );
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::song_compare::ReferenceAnalysisFailureDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(
                <crate::api::song_compare::ReferenceAnalysisFailureDto>::sse_decode(deserializer),
            );
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::song_compare::ReferenceAnalysisReportDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(
                <crate::api::song_compare::ReferenceAnalysisReportDto>::sse_decode(deserializer),
            );
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::realtime::RobustStabilityDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::realtime::RobustStabilityDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::song::SongSeparationFailureDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::song::SongSeparationFailureDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::song::SongSeparationProgressDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::song::SongSeparationProgressDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::song::SongSeparationReportDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::song::SongSeparationReportDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::song_compare::ReferenceAnalysisEventDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_progress = <Option<f64>>::sse_decode(deserializer);
        let mut var_report =
            <Option<crate::api::song_compare::ReferenceAnalysisReportDto>>::sse_decode(
                deserializer,
            );
        let mut var_failure =
            <Option<crate::api::song_compare::ReferenceAnalysisFailureDto>>::sse_decode(
                deserializer,
            );
        return crate::api::song_compare::ReferenceAnalysisEventDto {
            kind: var_kind,
            progress: var_progress,
            report: var_report,
            failure: var_failure,
        };
    }
}

impl SseDecode for crate::api::song_compare::ReferenceAnalysisFailureDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_reason = <String>::sse_decode(deserializer);
        let mut var_detail = <String>::sse_decode(deserializer);
        return crate::api::song_compare::ReferenceAnalysisFailureDto {
            reason: var_reason,
            detail: var_detail,
        };
    }
}

impl SseDecode for crate::api::song_compare::ReferenceAnalysisReportDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sampleRate = <u32>::sse_decode(deserializer);
        let mut var_frameRateHz = <u32>::sse_decode(deserializer);
        let mut var_algorithmVersion = <String>::sse_decode(deserializer);
        let mut var_frames =
            <Vec<crate::api::song_compare::ReferenceFeatureFrameDto>>::sse_decode(deserializer);
        return crate::api::song_compare::ReferenceAnalysisReportDto {
            sample_rate: var_sampleRate,
            frame_rate_hz: var_frameRateHz,
            algorithm_version: var_algorithmVersion,
            frames: var_frames,
        };
    }
}

impl SseDecode for crate::api::song_compare::ReferenceAnalysisRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_vocalsPath = <String>::sse_decode(deserializer);
        let mut var_maximumDecodedFrames = <u64>::sse_decode(deserializer);
        let mut var_cancelMarker = <String>::sse_decode(deserializer);
        return crate::api::song_compare::ReferenceAnalysisRequestDto {
            vocals_path: var_vocalsPath,
            maximum_decoded_frames: var_maximumDecodedFrames,
            cancel_marker: var_cancelMarker,
        };
    }
}

impl SseDecode for crate::api::song_compare::ReferenceFeatureFrameDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sampleIndex = <u64>::sse_decode(deserializer);
        let mut var_pitchCents = <Option<f64>>::sse_decode(deserializer);
        let mut var_rmsDbfs = <f64>::sse_decode(deserializer);
        let mut var_periodicity = <f64>::sse_decode(deserializer);
        let mut var_voiced = <bool>::sse_decode(deserializer);
        let mut var_clipping = <bool>::sse_decode(deserializer);
        return crate::api::song_compare::ReferenceFeatureFrameDto {
            sample_index: var_sampleIndex,
            pitch_cents: var_pitchCents,
            rms_dbfs: var_rmsDbfs,
            periodicity: var_periodicity,
            voiced: var_voiced,
            clipping: var_clipping,
        };
    }
}

impl SseDecode for crate::api::realtime::RobustStabilityDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_median = <f32>::sse_decode(deserializer);
        let mut var_medianAbsoluteDeviation = <f32>::sse_decode(deserializer);
        let mut var_slopePerSecond = <f32>::sse_decode(deserializer);
        let mut var_frameCount = <u32>::sse_decode(deserializer);
        return crate::api::realtime::RobustStabilityDto {
            median: var_median,
            median_absolute_deviation: var_medianAbsoluteDeviation,
            slope_per_second: var_slopePerSecond,
            frame_count: var_frameCount,
        };
    }
}

impl SseDecode for crate::api::realtime::SegmentSummaryDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_startSample = <Option<u64>>::sse_decode(deserializer);
        let mut var_endSample = <Option<u64>>::sse_decode(deserializer);
        let mut var_frameCount = <u32>::sse_decode(deserializer);
        let mut var_validFrameCount = <u32>::sse_decode(deserializer);
        let mut var_droppedSamples = <u64>::sse_decode(deserializer);
        let mut var_qualityFlags = <u16>::sse_decode(deserializer);
        let mut var_pitchStability =
            <Option<crate::api::realtime::RobustStabilityDto>>::sse_decode(deserializer);
        let mut var_levelStability =
            <Option<crate::api::realtime::RobustStabilityDto>>::sse_decode(deserializer);
        let mut var_onsetDelaySamples = <Option<u64>>::sse_decode(deserializer);
        return crate::api::realtime::SegmentSummaryDto {
            start_sample: var_startSample,
            end_sample: var_endSample,
            frame_count: var_frameCount,
            valid_frame_count: var_validFrameCount,
            dropped_samples: var_droppedSamples,
            quality_flags: var_qualityFlags,
            pitch_stability: var_pitchStability,
            level_stability: var_levelStability,
            onset_delay_samples: var_onsetDelaySamples,
        };
    }
}

impl SseDecode for crate::api::song::SongRuntimeStatusDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_available = <bool>::sse_decode(deserializer);
        let mut var_reason = <Option<String>>::sse_decode(deserializer);
        let mut var_modelId = <Option<String>>::sse_decode(deserializer);
        return crate::api::song::SongRuntimeStatusDto {
            available: var_available,
            reason: var_reason,
            model_id: var_modelId,
        };
    }
}

impl SseDecode for crate::api::song::SongSeparationEventDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_progress =
            <Option<crate::api::song::SongSeparationProgressDto>>::sse_decode(deserializer);
        let mut var_report =
            <Option<crate::api::song::SongSeparationReportDto>>::sse_decode(deserializer);
        let mut var_failure =
            <Option<crate::api::song::SongSeparationFailureDto>>::sse_decode(deserializer);
        return crate::api::song::SongSeparationEventDto {
            kind: var_kind,
            progress: var_progress,
            report: var_report,
            failure: var_failure,
        };
    }
}

impl SseDecode for crate::api::song::SongSeparationFailureDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_reason = <String>::sse_decode(deserializer);
        let mut var_operation = <String>::sse_decode(deserializer);
        let mut var_detail = <String>::sse_decode(deserializer);
        return crate::api::song::SongSeparationFailureDto {
            reason: var_reason,
            operation: var_operation,
            detail: var_detail,
        };
    }
}

impl SseDecode for crate::api::song::SongSeparationProgressDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_stage = <String>::sse_decode(deserializer);
        let mut var_completedUnits = <u64>::sse_decode(deserializer);
        let mut var_totalUnits = <u64>::sse_decode(deserializer);
        return crate::api::song::SongSeparationProgressDto {
            stage: var_stage,
            completed_units: var_completedUnits,
            total_units: var_totalUnits,
        };
    }
}

impl SseDecode for crate::api::song::SongSeparationReportDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_modelId = <String>::sse_decode(deserializer);
        let mut var_algorithmVersion = <String>::sse_decode(deserializer);
        let mut var_sourceSampleRate = <u32>::sse_decode(deserializer);
        let mut var_sourceChannels = <u16>::sse_decode(deserializer);
        let mut var_outputSampleRate = <u32>::sse_decode(deserializer);
        let mut var_outputChannels = <u16>::sse_decode(deserializer);
        let mut var_outputFrames = <u64>::sse_decode(deserializer);
        let mut var_chunkCount = <u32>::sse_decode(deserializer);
        let mut var_vocals = <crate::api::song::SongStemMetadataDto>::sse_decode(deserializer);
        let mut var_accompaniment =
            <crate::api::song::SongStemMetadataDto>::sse_decode(deserializer);
        return crate::api::song::SongSeparationReportDto {
            model_id: var_modelId,
            algorithm_version: var_algorithmVersion,
            source_sample_rate: var_sourceSampleRate,
            source_channels: var_sourceChannels,
            output_sample_rate: var_outputSampleRate,
            output_channels: var_outputChannels,
            output_frames: var_outputFrames,
            chunk_count: var_chunkCount,
            vocals: var_vocals,
            accompaniment: var_accompaniment,
        };
    }
}

impl SseDecode for crate::api::song::SongSeparationRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_rightsAcknowledged = <bool>::sse_decode(deserializer);
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_modelPath = <String>::sse_decode(deserializer);
        let mut var_expectedModelSha256 = <String>::sse_decode(deserializer);
        let mut var_outputDirectory = <String>::sse_decode(deserializer);
        let mut var_jobId = <String>::sse_decode(deserializer);
        let mut var_cancelMarker = <String>::sse_decode(deserializer);
        let mut var_maximumDecodedFrames = <u64>::sse_decode(deserializer);
        return crate::api::song::SongSeparationRequestDto {
            rights_acknowledged: var_rightsAcknowledged,
            input_path: var_inputPath,
            model_path: var_modelPath,
            expected_model_sha256: var_expectedModelSha256,
            output_directory: var_outputDirectory,
            job_id: var_jobId,
            cancel_marker: var_cancelMarker,
            maximum_decoded_frames: var_maximumDecodedFrames,
        };
    }
}

impl SseDecode for crate::api::song::SongStemMetadataDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_sha256 = <String>::sse_decode(deserializer);
        let mut var_byteLength = <u64>::sse_decode(deserializer);
        return crate::api::song::SongStemMetadataDto {
            path: var_path,
            sha256: var_sha256,
            byte_length: var_byteLength,
        };
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__realtime__RealtimeAnalyzer_finish_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__realtime__RealtimeAnalyzer_new_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__realtime__RealtimeAnalyzer_push_pcm16_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        4 => wire__crate__api__realtime__RealtimeAnalyzer_push_pcm16_at_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__api__realtime__RealtimeAnalyzer_push_pcm16_with_metadata_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        6 => wire__crate__api__realtime__RealtimeAnalyzer_reset_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__simple__init_app_impl(ptr, rust_vec_len, data_len),
        9 => {
            wire__crate__api__song__probe_song_separation_runtime_impl(ptr, rust_vec_len, data_len)
        }
        10 => wire__crate__api__song_compare__start_reference_analysis_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        11 => wire__crate__api__song__start_song_separation_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<RealtimeAnalyzer> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<RealtimeAnalyzer> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<RealtimeAnalyzer>> for RealtimeAnalyzer {
    fn into_into_dart(self) -> FrbWrapper<RealtimeAnalyzer> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::realtime::AnalysisFrameDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.start_sample.into_into_dart().into_dart(),
            self.rms_dbfs.into_into_dart().into_dart(),
            self.peak_dbfs.into_into_dart().into_dart(),
            self.pitch_hz.into_into_dart().into_dart(),
            self.pitch_clarity.into_into_dart().into_dart(),
            self.voiced.into_into_dart().into_dart(),
            self.band_powers_dbfs.into_into_dart().into_dart(),
            self.quality_flags.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::realtime::AnalysisFrameDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::realtime::AnalysisFrameDto>
    for crate::api::realtime::AnalysisFrameDto
{
    fn into_into_dart(self) -> crate::api::realtime::AnalysisFrameDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::song_compare::ReferenceAnalysisEventDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.progress.into_into_dart().into_dart(),
            self.report.into_into_dart().into_dart(),
            self.failure.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::song_compare::ReferenceAnalysisEventDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::song_compare::ReferenceAnalysisEventDto>
    for crate::api::song_compare::ReferenceAnalysisEventDto
{
    fn into_into_dart(self) -> crate::api::song_compare::ReferenceAnalysisEventDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::song_compare::ReferenceAnalysisFailureDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.reason.into_into_dart().into_dart(),
            self.detail.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::song_compare::ReferenceAnalysisFailureDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::song_compare::ReferenceAnalysisFailureDto>
    for crate::api::song_compare::ReferenceAnalysisFailureDto
{
    fn into_into_dart(self) -> crate::api::song_compare::ReferenceAnalysisFailureDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::song_compare::ReferenceAnalysisReportDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.sample_rate.into_into_dart().into_dart(),
            self.frame_rate_hz.into_into_dart().into_dart(),
            self.algorithm_version.into_into_dart().into_dart(),
            self.frames.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::song_compare::ReferenceAnalysisReportDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::song_compare::ReferenceAnalysisReportDto>
    for crate::api::song_compare::ReferenceAnalysisReportDto
{
    fn into_into_dart(self) -> crate::api::song_compare::ReferenceAnalysisReportDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::song_compare::ReferenceAnalysisRequestDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.vocals_path.into_into_dart().into_dart(),
            self.maximum_decoded_frames.into_into_dart().into_dart(),
            self.cancel_marker.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::song_compare::ReferenceAnalysisRequestDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::song_compare::ReferenceAnalysisRequestDto>
    for crate::api::song_compare::ReferenceAnalysisRequestDto
{
    fn into_into_dart(self) -> crate::api::song_compare::ReferenceAnalysisRequestDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::song_compare::ReferenceFeatureFrameDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.sample_index.into_into_dart().into_dart(),
            self.pitch_cents.into_into_dart().into_dart(),
            self.rms_dbfs.into_into_dart().into_dart(),
            self.periodicity.into_into_dart().into_dart(),
            self.voiced.into_into_dart().into_dart(),
            self.clipping.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::song_compare::ReferenceFeatureFrameDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::song_compare::ReferenceFeatureFrameDto>
    for crate::api::song_compare::ReferenceFeatureFrameDto
{
    fn into_into_dart(self) -> crate::api::song_compare::ReferenceFeatureFrameDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::realtime::RobustStabilityDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.median.into_into_dart().into_dart(),
            self.median_absolute_deviation.into_into_dart().into_dart(),
            self.slope_per_second.into_into_dart().into_dart(),
            self.frame_count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::realtime::RobustStabilityDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::realtime::RobustStabilityDto>
    for crate::api::realtime::RobustStabilityDto
{
    fn into_into_dart(self) -> crate::api::realtime::RobustStabilityDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::realtime::SegmentSummaryDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.start_sample.into_into_dart().into_dart(),
            self.end_sample.into_into_dart().into_dart(),
            self.frame_count.into_into_dart().into_dart(),
            self.valid_frame_count.into_into_dart().into_dart(),
            self.dropped_samples.into_into_dart().into_dart(),
            self.quality_flags.into_into_dart().into_dart(),
            self.pitch_stability.into_into_dart().into_dart(),
            self.level_stability.into_into_dart().into_dart(),
            self.onset_delay_samples.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::realtime::SegmentSummaryDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::realtime::SegmentSummaryDto>
    for crate::api::realtime::SegmentSummaryDto
{
    fn into_into_dart(self) -> crate::api::realtime::SegmentSummaryDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::song::SongRuntimeStatusDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.available.into_into_dart().into_dart(),
            self.reason.into_into_dart().into_dart(),
            self.model_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::song::SongRuntimeStatusDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::song::SongRuntimeStatusDto>
    for crate::api::song::SongRuntimeStatusDto
{
    fn into_into_dart(self) -> crate::api::song::SongRuntimeStatusDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::song::SongSeparationEventDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.progress.into_into_dart().into_dart(),
            self.report.into_into_dart().into_dart(),
            self.failure.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::song::SongSeparationEventDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::song::SongSeparationEventDto>
    for crate::api::song::SongSeparationEventDto
{
    fn into_into_dart(self) -> crate::api::song::SongSeparationEventDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::song::SongSeparationFailureDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.reason.into_into_dart().into_dart(),
            self.operation.into_into_dart().into_dart(),
            self.detail.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::song::SongSeparationFailureDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::song::SongSeparationFailureDto>
    for crate::api::song::SongSeparationFailureDto
{
    fn into_into_dart(self) -> crate::api::song::SongSeparationFailureDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::song::SongSeparationProgressDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.stage.into_into_dart().into_dart(),
            self.completed_units.into_into_dart().into_dart(),
            self.total_units.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::song::SongSeparationProgressDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::song::SongSeparationProgressDto>
    for crate::api::song::SongSeparationProgressDto
{
    fn into_into_dart(self) -> crate::api::song::SongSeparationProgressDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::song::SongSeparationReportDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.model_id.into_into_dart().into_dart(),
            self.algorithm_version.into_into_dart().into_dart(),
            self.source_sample_rate.into_into_dart().into_dart(),
            self.source_channels.into_into_dart().into_dart(),
            self.output_sample_rate.into_into_dart().into_dart(),
            self.output_channels.into_into_dart().into_dart(),
            self.output_frames.into_into_dart().into_dart(),
            self.chunk_count.into_into_dart().into_dart(),
            self.vocals.into_into_dart().into_dart(),
            self.accompaniment.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::song::SongSeparationReportDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::song::SongSeparationReportDto>
    for crate::api::song::SongSeparationReportDto
{
    fn into_into_dart(self) -> crate::api::song::SongSeparationReportDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::song::SongSeparationRequestDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.rights_acknowledged.into_into_dart().into_dart(),
            self.input_path.into_into_dart().into_dart(),
            self.model_path.into_into_dart().into_dart(),
            self.expected_model_sha256.into_into_dart().into_dart(),
            self.output_directory.into_into_dart().into_dart(),
            self.job_id.into_into_dart().into_dart(),
            self.cancel_marker.into_into_dart().into_dart(),
            self.maximum_decoded_frames.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::song::SongSeparationRequestDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::song::SongSeparationRequestDto>
    for crate::api::song::SongSeparationRequestDto
{
    fn into_into_dart(self) -> crate::api::song::SongSeparationRequestDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::song::SongStemMetadataDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.path.into_into_dart().into_dart(),
            self.sha256.into_into_dart().into_dart(),
            self.byte_length.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::song::SongStemMetadataDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::song::SongStemMetadataDto>
    for crate::api::song::SongStemMetadataDto
{
    fn into_into_dart(self) -> crate::api::song::SongStemMetadataDto {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for RealtimeAnalyzer {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>>>::sse_encode(flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self), serializer);
    }
}

impl SseEncode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode
    for StreamSink<
        crate::api::song_compare::ReferenceAnalysisEventDto,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::song::SongRuntimeStatusDto,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::song::SongSeparationEventDto,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::realtime::AnalysisFrameDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.start_sample, serializer);
        <f32>::sse_encode(self.rms_dbfs, serializer);
        <f32>::sse_encode(self.peak_dbfs, serializer);
        <Option<f32>>::sse_encode(self.pitch_hz, serializer);
        <f32>::sse_encode(self.pitch_clarity, serializer);
        <bool>::sse_encode(self.voiced, serializer);
        <Vec<f32>>::sse_encode(self.band_powers_dbfs, serializer);
        <u16>::sse_encode(self.quality_flags, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::realtime::AnalysisFrameDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::realtime::AnalysisFrameDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <f32>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<i16> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <i16>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::song_compare::ReferenceFeatureFrameDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::song_compare::ReferenceFeatureFrameDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::song_compare::ReferenceAnalysisFailureDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::song_compare::ReferenceAnalysisFailureDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::song_compare::ReferenceAnalysisReportDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::song_compare::ReferenceAnalysisReportDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::realtime::RobustStabilityDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::realtime::RobustStabilityDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::song::SongSeparationFailureDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::song::SongSeparationFailureDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::song::SongSeparationProgressDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::song::SongSeparationProgressDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::song::SongSeparationReportDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::song::SongSeparationReportDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::song_compare::ReferenceAnalysisEventDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.kind, serializer);
        <Option<f64>>::sse_encode(self.progress, serializer);
        <Option<crate::api::song_compare::ReferenceAnalysisReportDto>>::sse_encode(
            self.report,
            serializer,
        );
        <Option<crate::api::song_compare::ReferenceAnalysisFailureDto>>::sse_encode(
            self.failure,
            serializer,
        );
    }
}

impl SseEncode for crate::api::song_compare::ReferenceAnalysisFailureDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.reason, serializer);
        <String>::sse_encode(self.detail, serializer);
    }
}

impl SseEncode for crate::api::song_compare::ReferenceAnalysisReportDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.sample_rate, serializer);
        <u32>::sse_encode(self.frame_rate_hz, serializer);
        <String>::sse_encode(self.algorithm_version, serializer);
        <Vec<crate::api::song_compare::ReferenceFeatureFrameDto>>::sse_encode(
            self.frames,
            serializer,
        );
    }
}

impl SseEncode for crate::api::song_compare::ReferenceAnalysisRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.vocals_path, serializer);
        <u64>::sse_encode(self.maximum_decoded_frames, serializer);
        <String>::sse_encode(self.cancel_marker, serializer);
    }
}

impl SseEncode for crate::api::song_compare::ReferenceFeatureFrameDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.sample_index, serializer);
        <Option<f64>>::sse_encode(self.pitch_cents, serializer);
        <f64>::sse_encode(self.rms_dbfs, serializer);
        <f64>::sse_encode(self.periodicity, serializer);
        <bool>::sse_encode(self.voiced, serializer);
        <bool>::sse_encode(self.clipping, serializer);
    }
}

impl SseEncode for crate::api::realtime::RobustStabilityDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.median, serializer);
        <f32>::sse_encode(self.median_absolute_deviation, serializer);
        <f32>::sse_encode(self.slope_per_second, serializer);
        <u32>::sse_encode(self.frame_count, serializer);
    }
}

impl SseEncode for crate::api::realtime::SegmentSummaryDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<u64>>::sse_encode(self.start_sample, serializer);
        <Option<u64>>::sse_encode(self.end_sample, serializer);
        <u32>::sse_encode(self.frame_count, serializer);
        <u32>::sse_encode(self.valid_frame_count, serializer);
        <u64>::sse_encode(self.dropped_samples, serializer);
        <u16>::sse_encode(self.quality_flags, serializer);
        <Option<crate::api::realtime::RobustStabilityDto>>::sse_encode(
            self.pitch_stability,
            serializer,
        );
        <Option<crate::api::realtime::RobustStabilityDto>>::sse_encode(
            self.level_stability,
            serializer,
        );
        <Option<u64>>::sse_encode(self.onset_delay_samples, serializer);
    }
}

impl SseEncode for crate::api::song::SongRuntimeStatusDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.available, serializer);
        <Option<String>>::sse_encode(self.reason, serializer);
        <Option<String>>::sse_encode(self.model_id, serializer);
    }
}

impl SseEncode for crate::api::song::SongSeparationEventDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.kind, serializer);
        <Option<crate::api::song::SongSeparationProgressDto>>::sse_encode(
            self.progress,
            serializer,
        );
        <Option<crate::api::song::SongSeparationReportDto>>::sse_encode(self.report, serializer);
        <Option<crate::api::song::SongSeparationFailureDto>>::sse_encode(self.failure, serializer);
    }
}

impl SseEncode for crate::api::song::SongSeparationFailureDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.reason, serializer);
        <String>::sse_encode(self.operation, serializer);
        <String>::sse_encode(self.detail, serializer);
    }
}

impl SseEncode for crate::api::song::SongSeparationProgressDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.stage, serializer);
        <u64>::sse_encode(self.completed_units, serializer);
        <u64>::sse_encode(self.total_units, serializer);
    }
}

impl SseEncode for crate::api::song::SongSeparationReportDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.model_id, serializer);
        <String>::sse_encode(self.algorithm_version, serializer);
        <u32>::sse_encode(self.source_sample_rate, serializer);
        <u16>::sse_encode(self.source_channels, serializer);
        <u32>::sse_encode(self.output_sample_rate, serializer);
        <u16>::sse_encode(self.output_channels, serializer);
        <u64>::sse_encode(self.output_frames, serializer);
        <u32>::sse_encode(self.chunk_count, serializer);
        <crate::api::song::SongStemMetadataDto>::sse_encode(self.vocals, serializer);
        <crate::api::song::SongStemMetadataDto>::sse_encode(self.accompaniment, serializer);
    }
}

impl SseEncode for crate::api::song::SongSeparationRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.rights_acknowledged, serializer);
        <String>::sse_encode(self.input_path, serializer);
        <String>::sse_encode(self.model_path, serializer);
        <String>::sse_encode(self.expected_model_sha256, serializer);
        <String>::sse_encode(self.output_directory, serializer);
        <String>::sse_encode(self.job_id, serializer);
        <String>::sse_encode(self.cancel_marker, serializer);
        <u64>::sse_encode(self.maximum_decoded_frames, serializer);
    }
}

impl SseEncode for crate::api::song::SongStemMetadataDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.path, serializer);
        <String>::sse_encode(self.sha256, serializer);
        <u64>::sse_encode(self.byte_length, serializer);
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use crate::api::realtime::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_voice_trainer_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>>::increment_strong_count(ptr as _);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_voice_trainer_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use crate::api::realtime::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    #[wasm_bindgen]
    pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>>::increment_strong_count(ptr as _);
    }

    #[wasm_bindgen]
    pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
