// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/realtime.dart';
import 'api/simple.dart';
import 'api/song.dart';
import 'api/song_compare.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RealtimeAnalyzerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RealtimeAnalyzer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    dynamic raw,
  );

  @protected
  RealtimeAnalyzer
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    dynamic raw,
  );

  @protected
  RealtimeAnalyzer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    dynamic raw,
  );

  @protected
  RustStreamSink<ReferenceAnalysisEventDto>
  dco_decode_StreamSink_reference_analysis_event_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<SongRuntimeStatusDto>
  dco_decode_StreamSink_song_runtime_status_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<SongSeparationEventDto>
  dco_decode_StreamSink_song_separation_event_dto_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnalysisFrameDto dco_decode_analysis_frame_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  ReferenceAnalysisFailureDto
  dco_decode_box_autoadd_reference_analysis_failure_dto(dynamic raw);

  @protected
  ReferenceAnalysisReportDto
  dco_decode_box_autoadd_reference_analysis_report_dto(dynamic raw);

  @protected
  ReferenceAnalysisRequestDto
  dco_decode_box_autoadd_reference_analysis_request_dto(dynamic raw);

  @protected
  RobustStabilityDto dco_decode_box_autoadd_robust_stability_dto(dynamic raw);

  @protected
  SongSeparationFailureDto dco_decode_box_autoadd_song_separation_failure_dto(
    dynamic raw,
  );

  @protected
  SongSeparationProgressDto dco_decode_box_autoadd_song_separation_progress_dto(
    dynamic raw,
  );

  @protected
  SongSeparationReportDto dco_decode_box_autoadd_song_separation_report_dto(
    dynamic raw,
  );

  @protected
  SongSeparationRequestDto dco_decode_box_autoadd_song_separation_request_dto(
    dynamic raw,
  );

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  List<AnalysisFrameDto> dco_decode_list_analysis_frame_dto(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_16_loose(dynamic raw);

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReferenceFeatureFrameDto> dco_decode_list_reference_feature_frame_dto(
    dynamic raw,
  );

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  ReferenceAnalysisFailureDto?
  dco_decode_opt_box_autoadd_reference_analysis_failure_dto(dynamic raw);

  @protected
  ReferenceAnalysisReportDto?
  dco_decode_opt_box_autoadd_reference_analysis_report_dto(dynamic raw);

  @protected
  RobustStabilityDto? dco_decode_opt_box_autoadd_robust_stability_dto(
    dynamic raw,
  );

  @protected
  SongSeparationFailureDto?
  dco_decode_opt_box_autoadd_song_separation_failure_dto(dynamic raw);

  @protected
  SongSeparationProgressDto?
  dco_decode_opt_box_autoadd_song_separation_progress_dto(dynamic raw);

  @protected
  SongSeparationReportDto?
  dco_decode_opt_box_autoadd_song_separation_report_dto(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  ReferenceAnalysisEventDto dco_decode_reference_analysis_event_dto(
    dynamic raw,
  );

  @protected
  ReferenceAnalysisFailureDto dco_decode_reference_analysis_failure_dto(
    dynamic raw,
  );

  @protected
  ReferenceAnalysisReportDto dco_decode_reference_analysis_report_dto(
    dynamic raw,
  );

  @protected
  ReferenceAnalysisRequestDto dco_decode_reference_analysis_request_dto(
    dynamic raw,
  );

  @protected
  ReferenceFeatureFrameDto dco_decode_reference_feature_frame_dto(dynamic raw);

  @protected
  RobustStabilityDto dco_decode_robust_stability_dto(dynamic raw);

  @protected
  SegmentSummaryDto dco_decode_segment_summary_dto(dynamic raw);

  @protected
  SongRuntimeStatusDto dco_decode_song_runtime_status_dto(dynamic raw);

  @protected
  SongSeparationEventDto dco_decode_song_separation_event_dto(dynamic raw);

  @protected
  SongSeparationFailureDto dco_decode_song_separation_failure_dto(dynamic raw);

  @protected
  SongSeparationProgressDto dco_decode_song_separation_progress_dto(
    dynamic raw,
  );

  @protected
  SongSeparationReportDto dco_decode_song_separation_report_dto(dynamic raw);

  @protected
  SongSeparationRequestDto dco_decode_song_separation_request_dto(dynamic raw);

  @protected
  SongStemMetadataDto dco_decode_song_stem_metadata_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RealtimeAnalyzer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    SseDeserializer deserializer,
  );

  @protected
  RealtimeAnalyzer
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    SseDeserializer deserializer,
  );

  @protected
  RealtimeAnalyzer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ReferenceAnalysisEventDto>
  sse_decode_StreamSink_reference_analysis_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SongRuntimeStatusDto>
  sse_decode_StreamSink_song_runtime_status_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SongSeparationEventDto>
  sse_decode_StreamSink_song_separation_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnalysisFrameDto sse_decode_analysis_frame_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  ReferenceAnalysisFailureDto
  sse_decode_box_autoadd_reference_analysis_failure_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceAnalysisReportDto
  sse_decode_box_autoadd_reference_analysis_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceAnalysisRequestDto
  sse_decode_box_autoadd_reference_analysis_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  RobustStabilityDto sse_decode_box_autoadd_robust_stability_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongSeparationFailureDto sse_decode_box_autoadd_song_separation_failure_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongSeparationProgressDto sse_decode_box_autoadd_song_separation_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongSeparationReportDto sse_decode_box_autoadd_song_separation_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongSeparationRequestDto sse_decode_box_autoadd_song_separation_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  List<AnalysisFrameDto> sse_decode_list_analysis_frame_dto(
    SseDeserializer deserializer,
  );

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_16_loose(SseDeserializer deserializer);

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReferenceFeatureFrameDto> sse_decode_list_reference_feature_frame_dto(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  ReferenceAnalysisFailureDto?
  sse_decode_opt_box_autoadd_reference_analysis_failure_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceAnalysisReportDto?
  sse_decode_opt_box_autoadd_reference_analysis_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  RobustStabilityDto? sse_decode_opt_box_autoadd_robust_stability_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongSeparationFailureDto?
  sse_decode_opt_box_autoadd_song_separation_failure_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongSeparationProgressDto?
  sse_decode_opt_box_autoadd_song_separation_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongSeparationReportDto?
  sse_decode_opt_box_autoadd_song_separation_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ReferenceAnalysisEventDto sse_decode_reference_analysis_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceAnalysisFailureDto sse_decode_reference_analysis_failure_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceAnalysisReportDto sse_decode_reference_analysis_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceAnalysisRequestDto sse_decode_reference_analysis_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReferenceFeatureFrameDto sse_decode_reference_feature_frame_dto(
    SseDeserializer deserializer,
  );

  @protected
  RobustStabilityDto sse_decode_robust_stability_dto(
    SseDeserializer deserializer,
  );

  @protected
  SegmentSummaryDto sse_decode_segment_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongRuntimeStatusDto sse_decode_song_runtime_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongSeparationEventDto sse_decode_song_separation_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongSeparationFailureDto sse_decode_song_separation_failure_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongSeparationProgressDto sse_decode_song_separation_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongSeparationReportDto sse_decode_song_separation_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongSeparationRequestDto sse_decode_song_separation_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongStemMetadataDto sse_decode_song_stem_metadata_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    RealtimeAnalyzer self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    RealtimeAnalyzer self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    RealtimeAnalyzer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_reference_analysis_event_dto_Sse(
    RustStreamSink<ReferenceAnalysisEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_song_runtime_status_dto_Sse(
    RustStreamSink<SongRuntimeStatusDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_song_separation_event_dto_Sse(
    RustStreamSink<SongSeparationEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_analysis_frame_dto(
    AnalysisFrameDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_reference_analysis_failure_dto(
    ReferenceAnalysisFailureDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reference_analysis_report_dto(
    ReferenceAnalysisReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reference_analysis_request_dto(
    ReferenceAnalysisRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_robust_stability_dto(
    RobustStabilityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_song_separation_failure_dto(
    SongSeparationFailureDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_song_separation_progress_dto(
    SongSeparationProgressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_song_separation_report_dto(
    SongSeparationReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_song_separation_request_dto(
    SongSeparationRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_analysis_frame_dto(
    List<AnalysisFrameDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_16_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_16_strict(
    Int16List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reference_feature_frame_dto(
    List<ReferenceFeatureFrameDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_reference_analysis_failure_dto(
    ReferenceAnalysisFailureDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_reference_analysis_report_dto(
    ReferenceAnalysisReportDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_robust_stability_dto(
    RobustStabilityDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_song_separation_failure_dto(
    SongSeparationFailureDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_song_separation_progress_dto(
    SongSeparationProgressDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_song_separation_report_dto(
    SongSeparationReportDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_reference_analysis_event_dto(
    ReferenceAnalysisEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reference_analysis_failure_dto(
    ReferenceAnalysisFailureDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reference_analysis_report_dto(
    ReferenceAnalysisReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reference_analysis_request_dto(
    ReferenceAnalysisRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reference_feature_frame_dto(
    ReferenceFeatureFrameDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_robust_stability_dto(
    RobustStabilityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_segment_summary_dto(
    SegmentSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_runtime_status_dto(
    SongRuntimeStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_separation_event_dto(
    SongSeparationEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_separation_failure_dto(
    SongSeparationFailureDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_separation_progress_dto(
    SongSeparationProgressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_separation_report_dto(
    SongSeparationReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_separation_request_dto(
    SongSeparationRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_stem_metadata_dto(
    SongStemMetadataDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    int ptr,
  );
}
