// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/realtime.dart';
import 'api/simple.dart';
import 'api/song.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 930316058;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_voice_trainer',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  SegmentSummaryDto crateApiRealtimeRealtimeAnalyzerFinish({
    required RealtimeAnalyzer that,
  });

  RealtimeAnalyzer crateApiRealtimeRealtimeAnalyzerNew({
    required int sampleRate,
  });

  List<AnalysisFrameDto> crateApiRealtimeRealtimeAnalyzerPushPcm16({
    required RealtimeAnalyzer that,
    required List<int> pcm,
  });

  List<AnalysisFrameDto> crateApiRealtimeRealtimeAnalyzerPushPcm16At({
    required RealtimeAnalyzer that,
    required BigInt startSample,
    required List<int> pcm,
  });

  List<AnalysisFrameDto> crateApiRealtimeRealtimeAnalyzerPushPcm16WithMetadata({
    required RealtimeAnalyzer that,
    required BigInt startSample,
    required List<int> pcm,
    required int droppedSamplesBefore,
    required bool discontinuityBefore,
  });

  void crateApiRealtimeRealtimeAnalyzerReset({required RealtimeAnalyzer that});

  String crateApiSimpleGreet({required String name});

  void crateApiSimpleInitApp();

  Future<SongRuntimeStatusDto> crateApiSongProbeSongSeparationRuntime({
    required String modelPath,
    required String expectedModelSha256,
  });

  Stream<SongSeparationEventDto> crateApiSongStartSongSeparation({
    required SongSeparationRequestDto request,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RealtimeAnalyzer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RealtimeAnalyzer;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RealtimeAnalyzerPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  SegmentSummaryDto crateApiRealtimeRealtimeAnalyzerFinish({
    required RealtimeAnalyzer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_segment_summary_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRealtimeRealtimeAnalyzerFinishConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRealtimeRealtimeAnalyzerFinishConstMeta =>
      const TaskConstMeta(
        debugName: "RealtimeAnalyzer_finish",
        argNames: ["that"],
      );

  @override
  RealtimeAnalyzer crateApiRealtimeRealtimeAnalyzerNew({
    required int sampleRate,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(sampleRate, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRealtimeRealtimeAnalyzerNewConstMeta,
        argValues: [sampleRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRealtimeRealtimeAnalyzerNewConstMeta =>
      const TaskConstMeta(
        debugName: "RealtimeAnalyzer_new",
        argNames: ["sampleRate"],
      );

  @override
  List<AnalysisFrameDto> crateApiRealtimeRealtimeAnalyzerPushPcm16({
    required RealtimeAnalyzer that,
    required List<int> pcm,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
            that,
            serializer,
          );
          sse_encode_list_prim_i_16_loose(pcm, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_analysis_frame_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRealtimeRealtimeAnalyzerPushPcm16ConstMeta,
        argValues: [that, pcm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRealtimeRealtimeAnalyzerPushPcm16ConstMeta =>
      const TaskConstMeta(
        debugName: "RealtimeAnalyzer_push_pcm16",
        argNames: ["that", "pcm"],
      );

  @override
  List<AnalysisFrameDto> crateApiRealtimeRealtimeAnalyzerPushPcm16At({
    required RealtimeAnalyzer that,
    required BigInt startSample,
    required List<int> pcm,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
            that,
            serializer,
          );
          sse_encode_u_64(startSample, serializer);
          sse_encode_list_prim_i_16_loose(pcm, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_analysis_frame_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRealtimeRealtimeAnalyzerPushPcm16AtConstMeta,
        argValues: [that, startSample, pcm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRealtimeRealtimeAnalyzerPushPcm16AtConstMeta =>
      const TaskConstMeta(
        debugName: "RealtimeAnalyzer_push_pcm16_at",
        argNames: ["that", "startSample", "pcm"],
      );

  @override
  List<AnalysisFrameDto> crateApiRealtimeRealtimeAnalyzerPushPcm16WithMetadata({
    required RealtimeAnalyzer that,
    required BigInt startSample,
    required List<int> pcm,
    required int droppedSamplesBefore,
    required bool discontinuityBefore,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
            that,
            serializer,
          );
          sse_encode_u_64(startSample, serializer);
          sse_encode_list_prim_i_16_loose(pcm, serializer);
          sse_encode_u_32(droppedSamplesBefore, serializer);
          sse_encode_bool(discontinuityBefore, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_analysis_frame_dto,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiRealtimeRealtimeAnalyzerPushPcm16WithMetadataConstMeta,
        argValues: [
          that,
          startSample,
          pcm,
          droppedSamplesBefore,
          discontinuityBefore,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiRealtimeRealtimeAnalyzerPushPcm16WithMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "RealtimeAnalyzer_push_pcm16_with_metadata",
        argNames: [
          "that",
          "startSample",
          "pcm",
          "droppedSamplesBefore",
          "discontinuityBefore",
        ],
      );

  @override
  void crateApiRealtimeRealtimeAnalyzerReset({required RealtimeAnalyzer that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRealtimeRealtimeAnalyzerResetConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRealtimeRealtimeAnalyzerResetConstMeta =>
      const TaskConstMeta(
        debugName: "RealtimeAnalyzer_reset",
        argNames: ["that"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  void crateApiSimpleInitApp() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<SongRuntimeStatusDto> crateApiSongProbeSongSeparationRuntime({
    required String modelPath,
    required String expectedModelSha256,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          sse_encode_String(expectedModelSha256, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_song_runtime_status_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongProbeSongSeparationRuntimeConstMeta,
        argValues: [modelPath, expectedModelSha256],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongProbeSongSeparationRuntimeConstMeta =>
      const TaskConstMeta(
        debugName: "probe_song_separation_runtime",
        argNames: ["modelPath", "expectedModelSha256"],
      );

  @override
  Stream<SongSeparationEventDto> crateApiSongStartSongSeparation({
    required SongSeparationRequestDto request,
  }) {
    final sink = RustStreamSink<SongSeparationEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_song_separation_request_dto(
              request,
              serializer,
            );
            sse_encode_StreamSink_song_separation_event_dto_Sse(
              sink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSongStartSongSeparationConstMeta,
          argValues: [request, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSongStartSongSeparationConstMeta =>
      const TaskConstMeta(
        debugName: "start_song_separation",
        argNames: ["request", "sink"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RealtimeAnalyzer => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RealtimeAnalyzer => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RealtimeAnalyzer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RealtimeAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RealtimeAnalyzer
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RealtimeAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RealtimeAnalyzer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RealtimeAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<SongSeparationEventDto>
  dco_decode_StreamSink_song_separation_event_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AnalysisFrameDto dco_decode_analysis_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return AnalysisFrameDto(
      startSample: dco_decode_u_64(arr[0]),
      rmsDbfs: dco_decode_f_32(arr[1]),
      peakDbfs: dco_decode_f_32(arr[2]),
      pitchHz: dco_decode_opt_box_autoadd_f_32(arr[3]),
      pitchClarity: dco_decode_f_32(arr[4]),
      voiced: dco_decode_bool(arr[5]),
      bandPowersDbfs: dco_decode_list_prim_f_32_strict(arr[6]),
      qualityFlags: dco_decode_u_16(arr[7]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  RobustStabilityDto dco_decode_box_autoadd_robust_stability_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_robust_stability_dto(raw);
  }

  @protected
  SongSeparationFailureDto dco_decode_box_autoadd_song_separation_failure_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_song_separation_failure_dto(raw);
  }

  @protected
  SongSeparationProgressDto dco_decode_box_autoadd_song_separation_progress_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_song_separation_progress_dto(raw);
  }

  @protected
  SongSeparationReportDto dco_decode_box_autoadd_song_separation_report_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_song_separation_report_dto(raw);
  }

  @protected
  SongSeparationRequestDto dco_decode_box_autoadd_song_separation_request_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_song_separation_request_dto(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<AnalysisFrameDto> dco_decode_list_analysis_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_analysis_frame_dto).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_i_16_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int16List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  RobustStabilityDto? dco_decode_opt_box_autoadd_robust_stability_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_robust_stability_dto(raw);
  }

  @protected
  SongSeparationFailureDto?
  dco_decode_opt_box_autoadd_song_separation_failure_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_song_separation_failure_dto(raw);
  }

  @protected
  SongSeparationProgressDto?
  dco_decode_opt_box_autoadd_song_separation_progress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_song_separation_progress_dto(raw);
  }

  @protected
  SongSeparationReportDto?
  dco_decode_opt_box_autoadd_song_separation_report_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_song_separation_report_dto(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  RobustStabilityDto dco_decode_robust_stability_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RobustStabilityDto(
      median: dco_decode_f_32(arr[0]),
      medianAbsoluteDeviation: dco_decode_f_32(arr[1]),
      slopePerSecond: dco_decode_f_32(arr[2]),
      frameCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  SegmentSummaryDto dco_decode_segment_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SegmentSummaryDto(
      startSample: dco_decode_opt_box_autoadd_u_64(arr[0]),
      endSample: dco_decode_opt_box_autoadd_u_64(arr[1]),
      frameCount: dco_decode_u_32(arr[2]),
      validFrameCount: dco_decode_u_32(arr[3]),
      droppedSamples: dco_decode_u_64(arr[4]),
      qualityFlags: dco_decode_u_16(arr[5]),
      pitchStability: dco_decode_opt_box_autoadd_robust_stability_dto(arr[6]),
      levelStability: dco_decode_opt_box_autoadd_robust_stability_dto(arr[7]),
      onsetDelaySamples: dco_decode_opt_box_autoadd_u_64(arr[8]),
    );
  }

  @protected
  SongRuntimeStatusDto dco_decode_song_runtime_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SongRuntimeStatusDto(
      available: dco_decode_bool(arr[0]),
      reason: dco_decode_opt_String(arr[1]),
      modelId: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  SongSeparationEventDto dco_decode_song_separation_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SongSeparationEventDto(
      kind: dco_decode_String(arr[0]),
      progress: dco_decode_opt_box_autoadd_song_separation_progress_dto(arr[1]),
      report: dco_decode_opt_box_autoadd_song_separation_report_dto(arr[2]),
      failure: dco_decode_opt_box_autoadd_song_separation_failure_dto(arr[3]),
    );
  }

  @protected
  SongSeparationFailureDto dco_decode_song_separation_failure_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SongSeparationFailureDto(
      reason: dco_decode_String(arr[0]),
      operation: dco_decode_String(arr[1]),
      detail: dco_decode_String(arr[2]),
    );
  }

  @protected
  SongSeparationProgressDto dco_decode_song_separation_progress_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SongSeparationProgressDto(
      stage: dco_decode_String(arr[0]),
      completedUnits: dco_decode_u_64(arr[1]),
      totalUnits: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  SongSeparationReportDto dco_decode_song_separation_report_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return SongSeparationReportDto(
      modelId: dco_decode_String(arr[0]),
      algorithmVersion: dco_decode_String(arr[1]),
      sourceSampleRate: dco_decode_u_32(arr[2]),
      sourceChannels: dco_decode_u_16(arr[3]),
      outputSampleRate: dco_decode_u_32(arr[4]),
      outputChannels: dco_decode_u_16(arr[5]),
      outputFrames: dco_decode_u_64(arr[6]),
      chunkCount: dco_decode_u_32(arr[7]),
      vocals: dco_decode_song_stem_metadata_dto(arr[8]),
      accompaniment: dco_decode_song_stem_metadata_dto(arr[9]),
    );
  }

  @protected
  SongSeparationRequestDto dco_decode_song_separation_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SongSeparationRequestDto(
      rightsAcknowledged: dco_decode_bool(arr[0]),
      inputPath: dco_decode_String(arr[1]),
      modelPath: dco_decode_String(arr[2]),
      expectedModelSha256: dco_decode_String(arr[3]),
      outputDirectory: dco_decode_String(arr[4]),
      jobId: dco_decode_String(arr[5]),
      cancelMarker: dco_decode_String(arr[6]),
      maximumDecodedFrames: dco_decode_u_64(arr[7]),
    );
  }

  @protected
  SongStemMetadataDto dco_decode_song_stem_metadata_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SongStemMetadataDto(
      path: dco_decode_String(arr[0]),
      sha256: dco_decode_String(arr[1]),
      byteLength: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RealtimeAnalyzer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RealtimeAnalyzerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RealtimeAnalyzer
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RealtimeAnalyzerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RealtimeAnalyzer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RealtimeAnalyzerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<SongSeparationEventDto>
  sse_decode_StreamSink_song_separation_event_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AnalysisFrameDto sse_decode_analysis_frame_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startSample = sse_decode_u_64(deserializer);
    var var_rmsDbfs = sse_decode_f_32(deserializer);
    var var_peakDbfs = sse_decode_f_32(deserializer);
    var var_pitchHz = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_pitchClarity = sse_decode_f_32(deserializer);
    var var_voiced = sse_decode_bool(deserializer);
    var var_bandPowersDbfs = sse_decode_list_prim_f_32_strict(deserializer);
    var var_qualityFlags = sse_decode_u_16(deserializer);
    return AnalysisFrameDto(
      startSample: var_startSample,
      rmsDbfs: var_rmsDbfs,
      peakDbfs: var_peakDbfs,
      pitchHz: var_pitchHz,
      pitchClarity: var_pitchClarity,
      voiced: var_voiced,
      bandPowersDbfs: var_bandPowersDbfs,
      qualityFlags: var_qualityFlags,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  RobustStabilityDto sse_decode_box_autoadd_robust_stability_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_robust_stability_dto(deserializer));
  }

  @protected
  SongSeparationFailureDto sse_decode_box_autoadd_song_separation_failure_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_song_separation_failure_dto(deserializer));
  }

  @protected
  SongSeparationProgressDto sse_decode_box_autoadd_song_separation_progress_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_song_separation_progress_dto(deserializer));
  }

  @protected
  SongSeparationReportDto sse_decode_box_autoadd_song_separation_report_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_song_separation_report_dto(deserializer));
  }

  @protected
  SongSeparationRequestDto sse_decode_box_autoadd_song_separation_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_song_separation_request_dto(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  List<AnalysisFrameDto> sse_decode_list_analysis_frame_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AnalysisFrameDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_analysis_frame_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_i_16_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RobustStabilityDto? sse_decode_opt_box_autoadd_robust_stability_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_robust_stability_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SongSeparationFailureDto?
  sse_decode_opt_box_autoadd_song_separation_failure_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_song_separation_failure_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SongSeparationProgressDto?
  sse_decode_opt_box_autoadd_song_separation_progress_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_song_separation_progress_dto(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  SongSeparationReportDto?
  sse_decode_opt_box_autoadd_song_separation_report_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_song_separation_report_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RobustStabilityDto sse_decode_robust_stability_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_median = sse_decode_f_32(deserializer);
    var var_medianAbsoluteDeviation = sse_decode_f_32(deserializer);
    var var_slopePerSecond = sse_decode_f_32(deserializer);
    var var_frameCount = sse_decode_u_32(deserializer);
    return RobustStabilityDto(
      median: var_median,
      medianAbsoluteDeviation: var_medianAbsoluteDeviation,
      slopePerSecond: var_slopePerSecond,
      frameCount: var_frameCount,
    );
  }

  @protected
  SegmentSummaryDto sse_decode_segment_summary_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startSample = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_endSample = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_frameCount = sse_decode_u_32(deserializer);
    var var_validFrameCount = sse_decode_u_32(deserializer);
    var var_droppedSamples = sse_decode_u_64(deserializer);
    var var_qualityFlags = sse_decode_u_16(deserializer);
    var var_pitchStability = sse_decode_opt_box_autoadd_robust_stability_dto(
      deserializer,
    );
    var var_levelStability = sse_decode_opt_box_autoadd_robust_stability_dto(
      deserializer,
    );
    var var_onsetDelaySamples = sse_decode_opt_box_autoadd_u_64(deserializer);
    return SegmentSummaryDto(
      startSample: var_startSample,
      endSample: var_endSample,
      frameCount: var_frameCount,
      validFrameCount: var_validFrameCount,
      droppedSamples: var_droppedSamples,
      qualityFlags: var_qualityFlags,
      pitchStability: var_pitchStability,
      levelStability: var_levelStability,
      onsetDelaySamples: var_onsetDelaySamples,
    );
  }

  @protected
  SongRuntimeStatusDto sse_decode_song_runtime_status_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_available = sse_decode_bool(deserializer);
    var var_reason = sse_decode_opt_String(deserializer);
    var var_modelId = sse_decode_opt_String(deserializer);
    return SongRuntimeStatusDto(
      available: var_available,
      reason: var_reason,
      modelId: var_modelId,
    );
  }

  @protected
  SongSeparationEventDto sse_decode_song_separation_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_progress = sse_decode_opt_box_autoadd_song_separation_progress_dto(
      deserializer,
    );
    var var_report = sse_decode_opt_box_autoadd_song_separation_report_dto(
      deserializer,
    );
    var var_failure = sse_decode_opt_box_autoadd_song_separation_failure_dto(
      deserializer,
    );
    return SongSeparationEventDto(
      kind: var_kind,
      progress: var_progress,
      report: var_report,
      failure: var_failure,
    );
  }

  @protected
  SongSeparationFailureDto sse_decode_song_separation_failure_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_reason = sse_decode_String(deserializer);
    var var_operation = sse_decode_String(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return SongSeparationFailureDto(
      reason: var_reason,
      operation: var_operation,
      detail: var_detail,
    );
  }

  @protected
  SongSeparationProgressDto sse_decode_song_separation_progress_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stage = sse_decode_String(deserializer);
    var var_completedUnits = sse_decode_u_64(deserializer);
    var var_totalUnits = sse_decode_u_64(deserializer);
    return SongSeparationProgressDto(
      stage: var_stage,
      completedUnits: var_completedUnits,
      totalUnits: var_totalUnits,
    );
  }

  @protected
  SongSeparationReportDto sse_decode_song_separation_report_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_modelId = sse_decode_String(deserializer);
    var var_algorithmVersion = sse_decode_String(deserializer);
    var var_sourceSampleRate = sse_decode_u_32(deserializer);
    var var_sourceChannels = sse_decode_u_16(deserializer);
    var var_outputSampleRate = sse_decode_u_32(deserializer);
    var var_outputChannels = sse_decode_u_16(deserializer);
    var var_outputFrames = sse_decode_u_64(deserializer);
    var var_chunkCount = sse_decode_u_32(deserializer);
    var var_vocals = sse_decode_song_stem_metadata_dto(deserializer);
    var var_accompaniment = sse_decode_song_stem_metadata_dto(deserializer);
    return SongSeparationReportDto(
      modelId: var_modelId,
      algorithmVersion: var_algorithmVersion,
      sourceSampleRate: var_sourceSampleRate,
      sourceChannels: var_sourceChannels,
      outputSampleRate: var_outputSampleRate,
      outputChannels: var_outputChannels,
      outputFrames: var_outputFrames,
      chunkCount: var_chunkCount,
      vocals: var_vocals,
      accompaniment: var_accompaniment,
    );
  }

  @protected
  SongSeparationRequestDto sse_decode_song_separation_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rightsAcknowledged = sse_decode_bool(deserializer);
    var var_inputPath = sse_decode_String(deserializer);
    var var_modelPath = sse_decode_String(deserializer);
    var var_expectedModelSha256 = sse_decode_String(deserializer);
    var var_outputDirectory = sse_decode_String(deserializer);
    var var_jobId = sse_decode_String(deserializer);
    var var_cancelMarker = sse_decode_String(deserializer);
    var var_maximumDecodedFrames = sse_decode_u_64(deserializer);
    return SongSeparationRequestDto(
      rightsAcknowledged: var_rightsAcknowledged,
      inputPath: var_inputPath,
      modelPath: var_modelPath,
      expectedModelSha256: var_expectedModelSha256,
      outputDirectory: var_outputDirectory,
      jobId: var_jobId,
      cancelMarker: var_cancelMarker,
      maximumDecodedFrames: var_maximumDecodedFrames,
    );
  }

  @protected
  SongStemMetadataDto sse_decode_song_stem_metadata_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    var var_byteLength = sse_decode_u_64(deserializer);
    return SongStemMetadataDto(
      path: var_path,
      sha256: var_sha256,
      byteLength: var_byteLength,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    RealtimeAnalyzer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RealtimeAnalyzerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    RealtimeAnalyzer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RealtimeAnalyzerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    RealtimeAnalyzer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RealtimeAnalyzerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_song_separation_event_dto_Sse(
    RustStreamSink<SongSeparationEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_song_separation_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_analysis_frame_dto(
    AnalysisFrameDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.startSample, serializer);
    sse_encode_f_32(self.rmsDbfs, serializer);
    sse_encode_f_32(self.peakDbfs, serializer);
    sse_encode_opt_box_autoadd_f_32(self.pitchHz, serializer);
    sse_encode_f_32(self.pitchClarity, serializer);
    sse_encode_bool(self.voiced, serializer);
    sse_encode_list_prim_f_32_strict(self.bandPowersDbfs, serializer);
    sse_encode_u_16(self.qualityFlags, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_robust_stability_dto(
    RobustStabilityDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_robust_stability_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_song_separation_failure_dto(
    SongSeparationFailureDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_song_separation_failure_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_song_separation_progress_dto(
    SongSeparationProgressDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_song_separation_progress_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_song_separation_report_dto(
    SongSeparationReportDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_song_separation_report_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_song_separation_request_dto(
    SongSeparationRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_song_separation_request_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_list_analysis_frame_dto(
    List<AnalysisFrameDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_analysis_frame_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_i_16_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(
      self is Int16List ? self : Int16List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_i_16_strict(
    Int16List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_robust_stability_dto(
    RobustStabilityDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_robust_stability_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_song_separation_failure_dto(
    SongSeparationFailureDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_song_separation_failure_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_song_separation_progress_dto(
    SongSeparationProgressDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_song_separation_progress_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_song_separation_report_dto(
    SongSeparationReportDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_song_separation_report_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_robust_stability_dto(
    RobustStabilityDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.median, serializer);
    sse_encode_f_32(self.medianAbsoluteDeviation, serializer);
    sse_encode_f_32(self.slopePerSecond, serializer);
    sse_encode_u_32(self.frameCount, serializer);
  }

  @protected
  void sse_encode_segment_summary_dto(
    SegmentSummaryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_64(self.startSample, serializer);
    sse_encode_opt_box_autoadd_u_64(self.endSample, serializer);
    sse_encode_u_32(self.frameCount, serializer);
    sse_encode_u_32(self.validFrameCount, serializer);
    sse_encode_u_64(self.droppedSamples, serializer);
    sse_encode_u_16(self.qualityFlags, serializer);
    sse_encode_opt_box_autoadd_robust_stability_dto(
      self.pitchStability,
      serializer,
    );
    sse_encode_opt_box_autoadd_robust_stability_dto(
      self.levelStability,
      serializer,
    );
    sse_encode_opt_box_autoadd_u_64(self.onsetDelaySamples, serializer);
  }

  @protected
  void sse_encode_song_runtime_status_dto(
    SongRuntimeStatusDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.available, serializer);
    sse_encode_opt_String(self.reason, serializer);
    sse_encode_opt_String(self.modelId, serializer);
  }

  @protected
  void sse_encode_song_separation_event_dto(
    SongSeparationEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_box_autoadd_song_separation_progress_dto(
      self.progress,
      serializer,
    );
    sse_encode_opt_box_autoadd_song_separation_report_dto(
      self.report,
      serializer,
    );
    sse_encode_opt_box_autoadd_song_separation_failure_dto(
      self.failure,
      serializer,
    );
  }

  @protected
  void sse_encode_song_separation_failure_dto(
    SongSeparationFailureDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.reason, serializer);
    sse_encode_String(self.operation, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_song_separation_progress_dto(
    SongSeparationProgressDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.stage, serializer);
    sse_encode_u_64(self.completedUnits, serializer);
    sse_encode_u_64(self.totalUnits, serializer);
  }

  @protected
  void sse_encode_song_separation_report_dto(
    SongSeparationReportDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.modelId, serializer);
    sse_encode_String(self.algorithmVersion, serializer);
    sse_encode_u_32(self.sourceSampleRate, serializer);
    sse_encode_u_16(self.sourceChannels, serializer);
    sse_encode_u_32(self.outputSampleRate, serializer);
    sse_encode_u_16(self.outputChannels, serializer);
    sse_encode_u_64(self.outputFrames, serializer);
    sse_encode_u_32(self.chunkCount, serializer);
    sse_encode_song_stem_metadata_dto(self.vocals, serializer);
    sse_encode_song_stem_metadata_dto(self.accompaniment, serializer);
  }

  @protected
  void sse_encode_song_separation_request_dto(
    SongSeparationRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.rightsAcknowledged, serializer);
    sse_encode_String(self.inputPath, serializer);
    sse_encode_String(self.modelPath, serializer);
    sse_encode_String(self.expectedModelSha256, serializer);
    sse_encode_String(self.outputDirectory, serializer);
    sse_encode_String(self.jobId, serializer);
    sse_encode_String(self.cancelMarker, serializer);
    sse_encode_u_64(self.maximumDecodedFrames, serializer);
  }

  @protected
  void sse_encode_song_stem_metadata_dto(
    SongStemMetadataDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.sha256, serializer);
    sse_encode_u_64(self.byteLength, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class RealtimeAnalyzerImpl extends RustOpaque implements RealtimeAnalyzer {
  // Not to be used by end users
  RealtimeAnalyzerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RealtimeAnalyzerImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RealtimeAnalyzer,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RealtimeAnalyzer,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_RealtimeAnalyzerPtr,
  );

  SegmentSummaryDto finish() =>
      RustLib.instance.api.crateApiRealtimeRealtimeAnalyzerFinish(that: this);

  List<AnalysisFrameDto> pushPcm16({required List<int> pcm}) => RustLib
      .instance
      .api
      .crateApiRealtimeRealtimeAnalyzerPushPcm16(that: this, pcm: pcm);

  /// Production entry point. Capture owns the monotonically increasing
  /// sample position; the DSP never invents a per-batch clock.
  List<AnalysisFrameDto> pushPcm16At({
    required BigInt startSample,
    required List<int> pcm,
  }) => RustLib.instance.api.crateApiRealtimeRealtimeAnalyzerPushPcm16At(
    that: this,
    startSample: startSample,
    pcm: pcm,
  );

  List<AnalysisFrameDto> pushPcm16WithMetadata({
    required BigInt startSample,
    required List<int> pcm,
    required int droppedSamplesBefore,
    required bool discontinuityBefore,
  }) => RustLib.instance.api
      .crateApiRealtimeRealtimeAnalyzerPushPcm16WithMetadata(
        that: this,
        startSample: startSample,
        pcm: pcm,
        droppedSamplesBefore: droppedSamplesBefore,
        discontinuityBefore: discontinuityBefore,
      );

  void reset() =>
      RustLib.instance.api.crateApiRealtimeRealtimeAnalyzerReset(that: this);
}
