// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/realtime.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -80312999;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_voice_trainer',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  SegmentSummaryDto crateApiRealtimeRealtimeAnalyzerFinish({
    required RealtimeAnalyzer that,
  });

  RealtimeAnalyzer crateApiRealtimeRealtimeAnalyzerNew({
    required int sampleRate,
  });

  List<AnalysisFrameDto> crateApiRealtimeRealtimeAnalyzerPushPcm16({
    required RealtimeAnalyzer that,
    required List<int> pcm,
  });

  List<AnalysisFrameDto> crateApiRealtimeRealtimeAnalyzerPushPcm16At({
    required RealtimeAnalyzer that,
    required BigInt startSample,
    required List<int> pcm,
  });

  List<AnalysisFrameDto> crateApiRealtimeRealtimeAnalyzerPushPcm16WithMetadata({
    required RealtimeAnalyzer that,
    required BigInt startSample,
    required List<int> pcm,
    required int droppedSamplesBefore,
    required bool discontinuityBefore,
  });

  void crateApiRealtimeRealtimeAnalyzerReset({required RealtimeAnalyzer that});

  String crateApiSimpleGreet({required String name});

  void crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RealtimeAnalyzer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RealtimeAnalyzer;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RealtimeAnalyzerPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  SegmentSummaryDto crateApiRealtimeRealtimeAnalyzerFinish({
    required RealtimeAnalyzer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_segment_summary_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRealtimeRealtimeAnalyzerFinishConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRealtimeRealtimeAnalyzerFinishConstMeta =>
      const TaskConstMeta(
        debugName: "RealtimeAnalyzer_finish",
        argNames: ["that"],
      );

  @override
  RealtimeAnalyzer crateApiRealtimeRealtimeAnalyzerNew({
    required int sampleRate,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(sampleRate, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRealtimeRealtimeAnalyzerNewConstMeta,
        argValues: [sampleRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRealtimeRealtimeAnalyzerNewConstMeta =>
      const TaskConstMeta(
        debugName: "RealtimeAnalyzer_new",
        argNames: ["sampleRate"],
      );

  @override
  List<AnalysisFrameDto> crateApiRealtimeRealtimeAnalyzerPushPcm16({
    required RealtimeAnalyzer that,
    required List<int> pcm,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
            that,
            serializer,
          );
          sse_encode_list_prim_i_16_loose(pcm, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_analysis_frame_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRealtimeRealtimeAnalyzerPushPcm16ConstMeta,
        argValues: [that, pcm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRealtimeRealtimeAnalyzerPushPcm16ConstMeta =>
      const TaskConstMeta(
        debugName: "RealtimeAnalyzer_push_pcm16",
        argNames: ["that", "pcm"],
      );

  @override
  List<AnalysisFrameDto> crateApiRealtimeRealtimeAnalyzerPushPcm16At({
    required RealtimeAnalyzer that,
    required BigInt startSample,
    required List<int> pcm,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
            that,
            serializer,
          );
          sse_encode_u_64(startSample, serializer);
          sse_encode_list_prim_i_16_loose(pcm, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_analysis_frame_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRealtimeRealtimeAnalyzerPushPcm16AtConstMeta,
        argValues: [that, startSample, pcm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRealtimeRealtimeAnalyzerPushPcm16AtConstMeta =>
      const TaskConstMeta(
        debugName: "RealtimeAnalyzer_push_pcm16_at",
        argNames: ["that", "startSample", "pcm"],
      );

  @override
  List<AnalysisFrameDto> crateApiRealtimeRealtimeAnalyzerPushPcm16WithMetadata({
    required RealtimeAnalyzer that,
    required BigInt startSample,
    required List<int> pcm,
    required int droppedSamplesBefore,
    required bool discontinuityBefore,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
            that,
            serializer,
          );
          sse_encode_u_64(startSample, serializer);
          sse_encode_list_prim_i_16_loose(pcm, serializer);
          sse_encode_u_32(droppedSamplesBefore, serializer);
          sse_encode_bool(discontinuityBefore, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_analysis_frame_dto,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiRealtimeRealtimeAnalyzerPushPcm16WithMetadataConstMeta,
        argValues: [
          that,
          startSample,
          pcm,
          droppedSamplesBefore,
          discontinuityBefore,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiRealtimeRealtimeAnalyzerPushPcm16WithMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "RealtimeAnalyzer_push_pcm16_with_metadata",
        argNames: [
          "that",
          "startSample",
          "pcm",
          "droppedSamplesBefore",
          "discontinuityBefore",
        ],
      );

  @override
  void crateApiRealtimeRealtimeAnalyzerReset({required RealtimeAnalyzer that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRealtimeRealtimeAnalyzerResetConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRealtimeRealtimeAnalyzerResetConstMeta =>
      const TaskConstMeta(
        debugName: "RealtimeAnalyzer_reset",
        argNames: ["that"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  void crateApiSimpleInitApp() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RealtimeAnalyzer => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RealtimeAnalyzer => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer;

  @protected
  RealtimeAnalyzer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RealtimeAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RealtimeAnalyzer
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RealtimeAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RealtimeAnalyzer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RealtimeAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AnalysisFrameDto dco_decode_analysis_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return AnalysisFrameDto(
      startSample: dco_decode_u_64(arr[0]),
      rmsDbfs: dco_decode_f_32(arr[1]),
      peakDbfs: dco_decode_f_32(arr[2]),
      pitchHz: dco_decode_opt_box_autoadd_f_32(arr[3]),
      pitchClarity: dco_decode_f_32(arr[4]),
      voiced: dco_decode_bool(arr[5]),
      bandPowersDbfs: dco_decode_list_prim_f_32_strict(arr[6]),
      qualityFlags: dco_decode_u_16(arr[7]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  RobustStabilityDto dco_decode_box_autoadd_robust_stability_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_robust_stability_dto(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<AnalysisFrameDto> dco_decode_list_analysis_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_analysis_frame_dto).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_i_16_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int16List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  RobustStabilityDto? dco_decode_opt_box_autoadd_robust_stability_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_robust_stability_dto(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  RobustStabilityDto dco_decode_robust_stability_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RobustStabilityDto(
      median: dco_decode_f_32(arr[0]),
      medianAbsoluteDeviation: dco_decode_f_32(arr[1]),
      slopePerSecond: dco_decode_f_32(arr[2]),
      frameCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  SegmentSummaryDto dco_decode_segment_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SegmentSummaryDto(
      startSample: dco_decode_opt_box_autoadd_u_64(arr[0]),
      endSample: dco_decode_opt_box_autoadd_u_64(arr[1]),
      frameCount: dco_decode_u_32(arr[2]),
      validFrameCount: dco_decode_u_32(arr[3]),
      droppedSamples: dco_decode_u_64(arr[4]),
      qualityFlags: dco_decode_u_16(arr[5]),
      pitchStability: dco_decode_opt_box_autoadd_robust_stability_dto(arr[6]),
      levelStability: dco_decode_opt_box_autoadd_robust_stability_dto(arr[7]),
      onsetDelaySamples: dco_decode_opt_box_autoadd_u_64(arr[8]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  RealtimeAnalyzer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RealtimeAnalyzerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RealtimeAnalyzer
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RealtimeAnalyzerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RealtimeAnalyzer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RealtimeAnalyzerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AnalysisFrameDto sse_decode_analysis_frame_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startSample = sse_decode_u_64(deserializer);
    var var_rmsDbfs = sse_decode_f_32(deserializer);
    var var_peakDbfs = sse_decode_f_32(deserializer);
    var var_pitchHz = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_pitchClarity = sse_decode_f_32(deserializer);
    var var_voiced = sse_decode_bool(deserializer);
    var var_bandPowersDbfs = sse_decode_list_prim_f_32_strict(deserializer);
    var var_qualityFlags = sse_decode_u_16(deserializer);
    return AnalysisFrameDto(
      startSample: var_startSample,
      rmsDbfs: var_rmsDbfs,
      peakDbfs: var_peakDbfs,
      pitchHz: var_pitchHz,
      pitchClarity: var_pitchClarity,
      voiced: var_voiced,
      bandPowersDbfs: var_bandPowersDbfs,
      qualityFlags: var_qualityFlags,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  RobustStabilityDto sse_decode_box_autoadd_robust_stability_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_robust_stability_dto(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  List<AnalysisFrameDto> sse_decode_list_analysis_frame_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AnalysisFrameDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_analysis_frame_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_i_16_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RobustStabilityDto? sse_decode_opt_box_autoadd_robust_stability_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_robust_stability_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RobustStabilityDto sse_decode_robust_stability_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_median = sse_decode_f_32(deserializer);
    var var_medianAbsoluteDeviation = sse_decode_f_32(deserializer);
    var var_slopePerSecond = sse_decode_f_32(deserializer);
    var var_frameCount = sse_decode_u_32(deserializer);
    return RobustStabilityDto(
      median: var_median,
      medianAbsoluteDeviation: var_medianAbsoluteDeviation,
      slopePerSecond: var_slopePerSecond,
      frameCount: var_frameCount,
    );
  }

  @protected
  SegmentSummaryDto sse_decode_segment_summary_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startSample = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_endSample = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_frameCount = sse_decode_u_32(deserializer);
    var var_validFrameCount = sse_decode_u_32(deserializer);
    var var_droppedSamples = sse_decode_u_64(deserializer);
    var var_qualityFlags = sse_decode_u_16(deserializer);
    var var_pitchStability = sse_decode_opt_box_autoadd_robust_stability_dto(
      deserializer,
    );
    var var_levelStability = sse_decode_opt_box_autoadd_robust_stability_dto(
      deserializer,
    );
    var var_onsetDelaySamples = sse_decode_opt_box_autoadd_u_64(deserializer);
    return SegmentSummaryDto(
      startSample: var_startSample,
      endSample: var_endSample,
      frameCount: var_frameCount,
      validFrameCount: var_validFrameCount,
      droppedSamples: var_droppedSamples,
      qualityFlags: var_qualityFlags,
      pitchStability: var_pitchStability,
      levelStability: var_levelStability,
      onsetDelaySamples: var_onsetDelaySamples,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    RealtimeAnalyzer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RealtimeAnalyzerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    RealtimeAnalyzer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RealtimeAnalyzerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealtimeAnalyzer(
    RealtimeAnalyzer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RealtimeAnalyzerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_analysis_frame_dto(
    AnalysisFrameDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.startSample, serializer);
    sse_encode_f_32(self.rmsDbfs, serializer);
    sse_encode_f_32(self.peakDbfs, serializer);
    sse_encode_opt_box_autoadd_f_32(self.pitchHz, serializer);
    sse_encode_f_32(self.pitchClarity, serializer);
    sse_encode_bool(self.voiced, serializer);
    sse_encode_list_prim_f_32_strict(self.bandPowersDbfs, serializer);
    sse_encode_u_16(self.qualityFlags, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_robust_stability_dto(
    RobustStabilityDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_robust_stability_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_list_analysis_frame_dto(
    List<AnalysisFrameDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_analysis_frame_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_i_16_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(
      self is Int16List ? self : Int16List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_i_16_strict(
    Int16List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_robust_stability_dto(
    RobustStabilityDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_robust_stability_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_robust_stability_dto(
    RobustStabilityDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.median, serializer);
    sse_encode_f_32(self.medianAbsoluteDeviation, serializer);
    sse_encode_f_32(self.slopePerSecond, serializer);
    sse_encode_u_32(self.frameCount, serializer);
  }

  @protected
  void sse_encode_segment_summary_dto(
    SegmentSummaryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_64(self.startSample, serializer);
    sse_encode_opt_box_autoadd_u_64(self.endSample, serializer);
    sse_encode_u_32(self.frameCount, serializer);
    sse_encode_u_32(self.validFrameCount, serializer);
    sse_encode_u_64(self.droppedSamples, serializer);
    sse_encode_u_16(self.qualityFlags, serializer);
    sse_encode_opt_box_autoadd_robust_stability_dto(
      self.pitchStability,
      serializer,
    );
    sse_encode_opt_box_autoadd_robust_stability_dto(
      self.levelStability,
      serializer,
    );
    sse_encode_opt_box_autoadd_u_64(self.onsetDelaySamples, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class RealtimeAnalyzerImpl extends RustOpaque implements RealtimeAnalyzer {
  // Not to be used by end users
  RealtimeAnalyzerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RealtimeAnalyzerImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RealtimeAnalyzer,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RealtimeAnalyzer,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_RealtimeAnalyzerPtr,
  );

  SegmentSummaryDto finish() =>
      RustLib.instance.api.crateApiRealtimeRealtimeAnalyzerFinish(that: this);

  List<AnalysisFrameDto> pushPcm16({required List<int> pcm}) => RustLib
      .instance
      .api
      .crateApiRealtimeRealtimeAnalyzerPushPcm16(that: this, pcm: pcm);

  /// Production entry point. Capture owns the monotonically increasing
  /// sample position; the DSP never invents a per-batch clock.
  List<AnalysisFrameDto> pushPcm16At({
    required BigInt startSample,
    required List<int> pcm,
  }) => RustLib.instance.api.crateApiRealtimeRealtimeAnalyzerPushPcm16At(
    that: this,
    startSample: startSample,
    pcm: pcm,
  );

  List<AnalysisFrameDto> pushPcm16WithMetadata({
    required BigInt startSample,
    required List<int> pcm,
    required int droppedSamplesBefore,
    required bool discontinuityBefore,
  }) => RustLib.instance.api
      .crateApiRealtimeRealtimeAnalyzerPushPcm16WithMetadata(
        that: this,
        startSample: startSample,
        pcm: pcm,
        droppedSamplesBefore: droppedSamplesBefore,
        discontinuityBefore: discontinuityBefore,
      );

  void reset() =>
      RustLib.instance.api.crateApiRealtimeRealtimeAnalyzerReset(that: this);
}
