// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AnalysisFrame {
  final BigInt startSample;
  final double rms;
  final double peak;
  final double spectralCentroidHz;
  final double? pitchHz;
  final double pitchClarity;

  const AnalysisFrame({
    required this.startSample,
    required this.rms,
    required this.peak,
    required this.spectralCentroidHz,
    this.pitchHz,
    required this.pitchClarity,
  });

  @override
  int get hashCode =>
      startSample.hashCode ^
      rms.hashCode ^
      peak.hashCode ^
      spectralCentroidHz.hashCode ^
      pitchHz.hashCode ^
      pitchClarity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalysisFrame &&
          runtimeType == other.runtimeType &&
          startSample == other.startSample &&
          rms == other.rms &&
          peak == other.peak &&
          spectralCentroidHz == other.spectralCentroidHz &&
          pitchHz == other.pitchHz &&
          pitchClarity == other.pitchClarity;
}
