// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeAnalyzer>>
abstract class RealtimeAnalyzer implements RustOpaqueInterface {
  factory RealtimeAnalyzer({required int sampleRate}) => RustLib.instance.api
      .crateApiRealtimeRealtimeAnalyzerNew(sampleRate: sampleRate);

  List<AnalysisFrame> pushPcm16({required List<int> pcm});

  void reset();
}
