// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failure_reason_name`, `probe_runtime_platform`, `stage_name`, `start_platform_separation`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Checks the reviewed hash and compiles the native model graph. It performs
/// no download and returns unavailable on Web, where no reviewed runtime has
/// passed the SRD-04 gate.
Future<SongRuntimeStatusDto> probeSongSeparationRuntime({
  required String modelPath,
  required String expectedModelSha256,
}) => RustLib.instance.api.crateApiSongProbeSongSeparationRuntime(
  modelPath: modelPath,
  expectedModelSha256: expectedModelSha256,
);

/// Runs the file-backed offline job on FRB's native worker and emits bounded
/// progress plus exactly one terminal completed/failed event.
Stream<SongSeparationEventDto> startSongSeparation({
  required SongSeparationRequestDto request,
}) => RustLib.instance.api.crateApiSongStartSongSeparation(request: request);

class SongRuntimeStatusDto {
  final bool available;
  final String? reason;
  final String? modelId;

  const SongRuntimeStatusDto({
    required this.available,
    this.reason,
    this.modelId,
  });

  @override
  int get hashCode => available.hashCode ^ reason.hashCode ^ modelId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongRuntimeStatusDto &&
          runtimeType == other.runtimeType &&
          available == other.available &&
          reason == other.reason &&
          modelId == other.modelId;
}

class SongSeparationEventDto {
  final String kind;
  final SongSeparationProgressDto? progress;
  final SongSeparationReportDto? report;
  final SongSeparationFailureDto? failure;

  const SongSeparationEventDto({
    required this.kind,
    this.progress,
    this.report,
    this.failure,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ progress.hashCode ^ report.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongSeparationEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          progress == other.progress &&
          report == other.report &&
          failure == other.failure;
}

class SongSeparationFailureDto {
  final String reason;
  final String operation;
  final String detail;

  const SongSeparationFailureDto({
    required this.reason,
    required this.operation,
    required this.detail,
  });

  @override
  int get hashCode => reason.hashCode ^ operation.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongSeparationFailureDto &&
          runtimeType == other.runtimeType &&
          reason == other.reason &&
          operation == other.operation &&
          detail == other.detail;
}

class SongSeparationProgressDto {
  final String stage;
  final BigInt completedUnits;
  final BigInt totalUnits;

  const SongSeparationProgressDto({
    required this.stage,
    required this.completedUnits,
    required this.totalUnits,
  });

  @override
  int get hashCode =>
      stage.hashCode ^ completedUnits.hashCode ^ totalUnits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongSeparationProgressDto &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          completedUnits == other.completedUnits &&
          totalUnits == other.totalUnits;
}

class SongSeparationReportDto {
  final String modelId;
  final String algorithmVersion;
  final int sourceSampleRate;
  final int sourceChannels;
  final int outputSampleRate;
  final int outputChannels;
  final BigInt outputFrames;
  final int chunkCount;
  final SongStemMetadataDto vocals;
  final SongStemMetadataDto accompaniment;

  const SongSeparationReportDto({
    required this.modelId,
    required this.algorithmVersion,
    required this.sourceSampleRate,
    required this.sourceChannels,
    required this.outputSampleRate,
    required this.outputChannels,
    required this.outputFrames,
    required this.chunkCount,
    required this.vocals,
    required this.accompaniment,
  });

  @override
  int get hashCode =>
      modelId.hashCode ^
      algorithmVersion.hashCode ^
      sourceSampleRate.hashCode ^
      sourceChannels.hashCode ^
      outputSampleRate.hashCode ^
      outputChannels.hashCode ^
      outputFrames.hashCode ^
      chunkCount.hashCode ^
      vocals.hashCode ^
      accompaniment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongSeparationReportDto &&
          runtimeType == other.runtimeType &&
          modelId == other.modelId &&
          algorithmVersion == other.algorithmVersion &&
          sourceSampleRate == other.sourceSampleRate &&
          sourceChannels == other.sourceChannels &&
          outputSampleRate == other.outputSampleRate &&
          outputChannels == other.outputChannels &&
          outputFrames == other.outputFrames &&
          chunkCount == other.chunkCount &&
          vocals == other.vocals &&
          accompaniment == other.accompaniment;
}

class SongSeparationRequestDto {
  final bool rightsAcknowledged;
  final String inputPath;
  final String modelPath;
  final String expectedModelSha256;
  final String outputDirectory;
  final String jobId;
  final String cancelMarker;
  final BigInt maximumDecodedFrames;

  const SongSeparationRequestDto({
    required this.rightsAcknowledged,
    required this.inputPath,
    required this.modelPath,
    required this.expectedModelSha256,
    required this.outputDirectory,
    required this.jobId,
    required this.cancelMarker,
    required this.maximumDecodedFrames,
  });

  @override
  int get hashCode =>
      rightsAcknowledged.hashCode ^
      inputPath.hashCode ^
      modelPath.hashCode ^
      expectedModelSha256.hashCode ^
      outputDirectory.hashCode ^
      jobId.hashCode ^
      cancelMarker.hashCode ^
      maximumDecodedFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongSeparationRequestDto &&
          runtimeType == other.runtimeType &&
          rightsAcknowledged == other.rightsAcknowledged &&
          inputPath == other.inputPath &&
          modelPath == other.modelPath &&
          expectedModelSha256 == other.expectedModelSha256 &&
          outputDirectory == other.outputDirectory &&
          jobId == other.jobId &&
          cancelMarker == other.cancelMarker &&
          maximumDecodedFrames == other.maximumDecodedFrames;
}

class SongStemMetadataDto {
  final String path;
  final String sha256;
  final BigInt byteLength;

  const SongStemMetadataDto({
    required this.path,
    required this.sha256,
    required this.byteLength,
  });

  @override
  int get hashCode => path.hashCode ^ sha256.hashCode ^ byteLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongStemMetadataDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          sha256 == other.sha256 &&
          byteLength == other.byteLength;
}
