// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `analyze_reference_file`, `failure_reason`, `run_native_analysis`, `spawn_platform_analysis`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Analyzes a local separated-vocals WAV on a native worker. Web has no
/// reviewed separator/reference file pipeline and returns typed unavailable.
Stream<ReferenceAnalysisEventDto> startReferenceAnalysis({
  required ReferenceAnalysisRequestDto request,
}) => RustLib.instance.api.crateApiSongCompareStartReferenceAnalysis(
  request: request,
);

class ReferenceAnalysisEventDto {
  final String kind;
  final double? progress;
  final ReferenceAnalysisReportDto? report;
  final ReferenceAnalysisFailureDto? failure;

  const ReferenceAnalysisEventDto({
    required this.kind,
    this.progress,
    this.report,
    this.failure,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ progress.hashCode ^ report.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReferenceAnalysisEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          progress == other.progress &&
          report == other.report &&
          failure == other.failure;
}

class ReferenceAnalysisFailureDto {
  final String reason;
  final String detail;

  const ReferenceAnalysisFailureDto({
    required this.reason,
    required this.detail,
  });

  @override
  int get hashCode => reason.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReferenceAnalysisFailureDto &&
          runtimeType == other.runtimeType &&
          reason == other.reason &&
          detail == other.detail;
}

class ReferenceAnalysisReportDto {
  final int sampleRate;
  final int frameRateHz;
  final String algorithmVersion;
  final List<ReferenceFeatureFrameDto> frames;

  const ReferenceAnalysisReportDto({
    required this.sampleRate,
    required this.frameRateHz,
    required this.algorithmVersion,
    required this.frames,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^
      frameRateHz.hashCode ^
      algorithmVersion.hashCode ^
      frames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReferenceAnalysisReportDto &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          frameRateHz == other.frameRateHz &&
          algorithmVersion == other.algorithmVersion &&
          frames == other.frames;
}

class ReferenceAnalysisRequestDto {
  final String vocalsPath;
  final BigInt maximumDecodedFrames;
  final String cancelMarker;

  const ReferenceAnalysisRequestDto({
    required this.vocalsPath,
    required this.maximumDecodedFrames,
    required this.cancelMarker,
  });

  @override
  int get hashCode =>
      vocalsPath.hashCode ^
      maximumDecodedFrames.hashCode ^
      cancelMarker.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReferenceAnalysisRequestDto &&
          runtimeType == other.runtimeType &&
          vocalsPath == other.vocalsPath &&
          maximumDecodedFrames == other.maximumDecodedFrames &&
          cancelMarker == other.cancelMarker;
}

class ReferenceFeatureFrameDto {
  final BigInt sampleIndex;
  final double? pitchCents;
  final double rmsDbfs;
  final double periodicity;
  final bool voiced;
  final bool clipping;

  const ReferenceFeatureFrameDto({
    required this.sampleIndex,
    this.pitchCents,
    required this.rmsDbfs,
    required this.periodicity,
    required this.voiced,
    required this.clipping,
  });

  @override
  int get hashCode =>
      sampleIndex.hashCode ^
      pitchCents.hashCode ^
      rmsDbfs.hashCode ^
      periodicity.hashCode ^
      voiced.hashCode ^
      clipping.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReferenceFeatureFrameDto &&
          runtimeType == other.runtimeType &&
          sampleIndex == other.sampleIndex &&
          pitchCents == other.pitchCents &&
          rmsDbfs == other.rmsDbfs &&
          periodicity == other.periodicity &&
          voiced == other.voiced &&
          clipping == other.clipping;
}
